kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim-xxx
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"   #与nfs-StorageClass.yaml metadata.name保持一致
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi  # 指定需要的空间大小
